"""
Django settings for datamodel_demo project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

from django.urls import reverse_lazy

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-f=w+e$yp_s&#oxk1r_0l_n#8t+4^3&6o@_21oyg-s8qob63f56"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["localhost", "127.0.0.1"]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:8000",
    "https://localhost:8000",
    "http://127.0.0.1:8000",
    "https://127.0.0.1:8000",
]


# Application definition

INSTALLED_APPS = [
    "app1",
    "unfold",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

UNFOLD = {
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "Tier 1: Core Provenance",
                "separator": True,
                "items": [
                    {
                        "title": "Entities",
                        "icon": "account_tree",
                        "link": reverse_lazy("admin:app1_entity_changelist"),
                    },
                    {
                        "title": "Activities",
                        "icon": "conversion_path",
                        "link": reverse_lazy("admin:app1_activity_changelist"),
                    },
                    {
                        "title": "Activity Entities",
                        "icon": "account_tree",
                        "link": reverse_lazy("admin:app1_activityentity_changelist"),
                    },
                    {
                        "title": "Entity Information Records",
                        "icon": "description",
                        "link": reverse_lazy("admin:app1_entityinformationrecord_changelist"),
                    },
                    {
                        "title": "Activity Information Records",
                        "icon": "event_note",
                        "link": reverse_lazy("admin:app1_activityinformationrecord_changelist"),
                    },
                    {
                        "title": "Entity Relations",
                        "icon": "account_tree",
                        "link": reverse_lazy("admin:app1_entityrelation_changelist"),
                    },
                ],
            },
            {
                "title": "Tier 2: Vocabularies and Configuration",
                "separator": True,
                "items": [
                    {
                        "title": "Entity Types",
                        "icon": "category",
                        "link": reverse_lazy("admin:app1_entitytype_changelist"),
                    },
                    {
                        "title": "Activity Types",
                        "icon": "account_tree",
                        "link": reverse_lazy("admin:app1_activitytype_changelist"),
                    },
                    {
                        "title": "Information Record Types",
                        "icon": "label",
                        "link": reverse_lazy("admin:app1_informationrecordtype_changelist"),
                    },
                    {
                        "title": "Parameter Definitions",
                        "icon": "tune",
                        "link": reverse_lazy("admin:app1_parameterdefinition_changelist"),
                    },
                    {
                        "title": "Protocols",
                        "icon": "menu_book",
                        "link": reverse_lazy("admin:app1_protocol_changelist"),
                    },
                    {
                        "title": "Protocol Parameters",
                        "icon": "tune",
                        "link": reverse_lazy("admin:app1_protocolparameter_changelist"),
                    },
                    {
                        "title": "Entity Relation Types",
                        "icon": "account_tree",
                        "link": reverse_lazy("admin:app1_entityrelationtype_changelist"),
                    },
                ],
            },
            {
                "title": "Tier 3: Extensions",
                "separator": True,
                "items": [],
            },
        ],
    },
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "datamodel_demo.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "datamodel_demo.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.environ.get("MYSQL_DATABASE", "sgbc_django"),
        "USER": os.environ.get("MYSQL_USER", "sgbc"),
        "PASSWORD": os.environ.get("MYSQL_PASSWORD", "sgbc_dev_password"),
        "HOST": os.environ.get("MYSQL_HOST", "127.0.0.1"),
        "PORT": os.environ.get("MYSQL_PORT", "3306"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = "static/"


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    "default": {
        "BACKEND": "django.core.mail.backends.console.EmailBackend",
    },
}
